/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;



/**
 *
 * @author user
 */
public class PenampilanGambarGUI extends javax.swing.JFrame {

    /**
     * Creates new form PenampilanGambarGUI
     */
    public PenampilanGambarGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonpanel = new javax.swing.JPanel();
        buttonbill = new javax.swing.JButton();
        buttonnadiem = new javax.swing.JButton();
        buttonwilliam = new javax.swing.JButton();
        buttonexit = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        labelbill = new javax.swing.JLabel();
        labelnadiem = new javax.swing.JLabel();
        labelwilliam = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penampilan Gambar");

        buttonbill.setText("Bill Gates");
        buttonbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbillActionPerformed(evt);
            }
        });
        buttonpanel.add(buttonbill);

        buttonnadiem.setText("Nadiem");
        buttonnadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnadiemActionPerformed(evt);
            }
        });
        buttonpanel.add(buttonnadiem);

        buttonwilliam.setText("William");
        buttonwilliam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonwilliamActionPerformed(evt);
            }
        });
        buttonpanel.add(buttonwilliam);

        buttonexit.setText("Exit");
        buttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonexitActionPerformed(evt);
            }
        });
        buttonpanel.add(buttonexit);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        imagepanel.setLayout(new java.awt.CardLayout());

        labelbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Bill Gates.jpg"))); // NOI18N
        labelbill.setToolTipText("null");
        imagepanel.add(labelbill, "0\n");

        labelnadiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Nadiem.jpg"))); // NOI18N
        labelnadiem.setToolTipText("null");
        imagepanel.add(labelnadiem, "1");

        labelwilliam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/william.jpg"))); // NOI18N
        imagepanel.add(labelwilliam, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbillActionPerformed
       CardLayout c1 = (CardLayout)(imagepanel.getLayout());
       c1.show(imagepanel, "0");
    }//GEN-LAST:event_buttonbillActionPerformed

    private void buttonnadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnadiemActionPerformed
        CardLayout c1 = (CardLayout)(imagepanel.getLayout());
       c1.show(imagepanel, "1");
    }//GEN-LAST:event_buttonnadiemActionPerformed

    private void buttonwilliamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonwilliamActionPerformed
        CardLayout c1 = (CardLayout)(imagepanel.getLayout());
       c1.show(imagepanel, "2");
    }//GEN-LAST:event_buttonwilliamActionPerformed

    private void buttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
        /* Set the //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilanGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilanGambarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbill;
    private javax.swing.JButton buttonexit;
    private javax.swing.JButton buttonnadiem;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JButton buttonwilliam;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel labelbill;
    private javax.swing.JLabel labelnadiem;
    private javax.swing.JLabel labelwilliam;
    // End of variables declaration//GEN-END:variables
}
